django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^trips/", include("trips.urls", namespace="trips")),
    url(r"^teams/", include("teams.urls", namespace="teams")),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'

urlpatterns = [
    url(r"^$", views.ListTeams.as_view(), name="all"),
    url(r"^new/$", views.CreateTeam.as_view(), name="create"),
    url(r"^trips/in/(?P<slug>[-\w]+)/$",
        views.SingleTeam.as_view(), name="single"),
    url(r"join/(?P<slug>[-\w]+)/$", views.JoinTeam.as_view(), name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveTeam.as_view(), name="leave"),
]

trips/urls.py
from django.conf.urls import url

from . import views

app_name = 'trips'

urlpatterns = [
    url(r"^$", views.TripList.as_view(), name="all"),
    url(r"new/$", views.CreateTrip.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserTrips.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.TripDetail.as_view(), name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeleteTrip.as_view(), name="delete"),
]

trips/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils import timezone
import misaka

from teams.models import Team

from django.contrib.auth import get_user_model
User = get_user_model()


class Trip(models.Model):
    user = models.ForeignKey(User, related_name="trips",
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    category = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    number = models.IntegerField()
    cost = models.IntegerField(default=0)
    receipt = models.ImageField(upload_to='image', default='Desert 3.jpg')
    reason = models.TextField()
    reason_html = models.TextField(editable=False)
    date = models.DateTimeField()
    team = models.ForeignKey(
        Team, related_name="trips", on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.category

    def save(self, *args, **kwargs):
        self.reason_html = misaka.html(self.reason)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "trips:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]

trips/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

class TripList(SelectRelatedMixin, generic.ListView):
    model = models.Trip
    select_related = ("user", "team")


class UserTrips(generic.ListView):
    model = models.Trip
    template_name = "trips/user_trip_list.html"

    def get_queryset(self):
        try:
            self.trip_user = User.objects.prefetch_related("trips").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.trip_user.trips.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trip_user"] = self.trip_user
        return context


class TripDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Trip
    select_related = ("user", "team")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreateTrip(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ("location","category","number","cost","receipt","date",'reason', 'team')
    model = models.Trip

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeleteTrip(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Trip
    select_related = ("user", "team")
    # go back to all the trips page
    success_url = reverse_lazy("trips:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Trip Deleted")
        return super().delete(*args, **kwargs)

trips/templates/trips/_trip.html
<div class="trip media">
      
      <dl>
      <h5><dt>Location</dt></h5>
      <dd><h6>{{trip.location}}</h6></dd>
      <h5><dt>Category</dt></h5>
      <dd><h6>{{trip.category}}</h6></dd>
      <h5><dt>Number</dt></h5>
      <dd><h6>{{trip.number}}</h6></dd>
      <h5><dt>Cost</dt></h5>
      <dd><h6>{{trip.cost}}</h6></dd>
      <h5><dt>Receipt</dt></h5>
      <dd><h6>{{trip.receipt}}</h6></dd>
      <h5><dt>Reason</dt></h5>
      <dd><h5>{{trip.reason_html|safe }}</h5></dd>
    </dl>
  
  <div class="media-body">
    <h6 class="media-heading">
      <span class="username"
        ><a href="{% url 'trips:for_user' username=trip.user.username %}"
          >@{{ trip.user.username }}</a
        > created at:</span
      >
      <time class="time">
      <a
          href="{% url 'trips:single' username=trip.user.username pk=trip.pk %}"
          >{{ trip.created_at }}</a
        >
     </time>
      {% if trip.team %}
      <span class="team-name">in <a href="{% url 'teams:single' slug=trip.team.slug %}">{{ trip.team.name }}</a></span>
      {% endif %}
    </h6>

    <div class="media-footer">
      {% if user.is_authenticated and trip.user == user and not hide_delete %}
      <a
        href="{% url 'trips:delete' pk=trip.pk %}"
        title="delete"
        class="btn btn-simple"
      >
        <span
          class="glyphicon glyphicon-remove text-danger"
          aria-hidden="true"
        ></span>
        <span class="text-danger icon-label">Delete</span>
      </a>
      {% endif %}
    </div>
  </div>
</div>

trips/templates/trips/trip_base.html
{% extends "base.html" %} {% block content %}
<div class="trips-page">
  <div class="container">
    <div class="row">
      {% block pretrip %}{% endblock %} {% block trip_content %}{% endblock %}
      {% block trip_trip %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

trips/templates/trips/trip_confirm_delete.html
{% extends "trips/trip_base.html" %} {% block trip_content %}
<h3>Are you sure you want to delete this trip?</h3>

<div class="trips">
  {% include "trips/_trip.html" with trip=object hide_delete=True %}
</div>

<form method="POST">
  {% csrf_token %}
  <input
    type="submit"
    value="Confirm Delete"
    class="btn btn-danger btn-large"
  />
  <a
    href="{% url 'trips:single' username=user.username pk=object.pk %}"
    class="btn btn-simple btn-large btn-default"
    >Cancel</a
  >
</form>

{% endblock %}

trips/templates/trips/trip_detail.html
{% extends "trips/trip_base.html" %} {% block trip_content %}
<div class="col-md-8">{% include "trips/_trip.html" %}</div>
{% endblock %}

trips/templates/trips/trip_form.html
{% extends "trips/trip_base.html" %}
{% load bootstrap3 %} 
{% block trip_content %}
{% comment %} {% if trip.user in team.members.all %} {% endcomment %}
<h4>Create New Trip</h4>
<br>
<form method="POST" action="{% url 'trips:create' %}" id="tripForm">
  {% csrf_token %} {% bootstrap_form form %}
  <input type="submit" value="Trip" class="btn btn-primary btn-large" />
</form>

{% endblock %}

trips/templates/trips/trip_list.html
{% extends "trips/trip_base.html" %} 
{% block pre_trip_content %}
<div class="col-md-4">
  {% if request.user.is_authenticated %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title">Your Teams</h5>
      <ul class="list-unstyled">
        {% for member_team in get_user_teams %}
        <li class="team li-with-bullet">
          <a href="{% url 'teams:single' slug=member_team.team.slug %}"
            >{{ member_team.team.name }}</a
          >
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title">All teams</h5>
      <ul class="list-unstyled">
        {% for other_team in get_other_teams %}
        <li class="team li-with-bullet">
          <a href="{% url 'teams:single' slug=other_team.slug %}"
            >{{ other_team.name }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endblock %} {% block trip_content %}
<div class="col-md-8">
  {% for trip in trip_list %} {% include "trips/_trip.html" %} {% endfor %}
</div>
{% endblock %}

trips/templates/trips/user_trip_list.html
{% extends "trips/trip_base.html" %} 
{% block pretrip %}
<div class="col-md-4">
  <h1>@{{ trip_user.username }}</h1>
  <p>All your trips >>> </p>
</div>
{% endblock %} 
{% block trip_content %}
<div class="col-md-8">
  {% for trip in trip_list %} {% include "trips/_trip.html" %} {% endfor %}
</div>
{% endblock %}