django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^trips/", include("trips.urls", namespace="trips")),
    url(r"^teams/", include("teams.urls", namespace="teams")),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'

urlpatterns = [
    url(r"^$", views.ListTeams.as_view(), name="all"),
    url(r"^new/$", views.CreateTeam.as_view(), name="create"),
    url(r"^trips/in/(?P<slug>[-\w]+)/$",
        views.SingleTeam.as_view(), name="single"),
    url(r"join/(?P<slug>[-\w]+)/$", views.JoinTeam.as_view(), name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveTeam.as_view(), name="leave"),
]

trips/urls.py
from django.conf.urls import url

from . import views

app_name = 'trips'

urlpatterns = [
    url(r"^$", views.TripList.as_view(), name="all"),
    url(r"new/$", views.CreateTrip.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserTrips.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.TripDetail.as_view(), name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeleteTrip.as_view(), name="delete"),
]

teams/models.py
from django import template
from django.db import models
# just allows us to remove any characters that are alphanumerics or underscores or hyphens and basically the idea behind that is if you have a string that has spaces in it and you want to use that as part of your URL it's going to be able to lowercase and add dashes instead of spaces.
from django.utils.text import slugify
# misaka allows us to actually do Lincoln betting.If you've ever use something like redit commenting system you can actually put links are a little bit a mark down text that that's what Misaka actually doee
import misaka
from django.urls import reverse
from django.utils import timezone
# Get user model returns the user model that's currently active in this project.
from django.contrib.auth import get_user_model
# allows us to do: E.G. call things off of the current user's session
User = get_user_model()
# this is how we can use custom template tags in the future.
register = template.Library()


class Team(models.Model):
    name = models.CharField(max_length=255, unique=True)
    team_leader = models.CharField(max_length=255)
    members = models.ManyToManyField(User, through="TeamMember")
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("teams:single", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["name"]


class TeamMember(models.Model):
    team = models.ForeignKey(
        Team, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name='user_teams', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('team', 'user')

teams/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)

from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404
from django.views import generic
from teams.models import Team, TeamMember
from . import models
from django.views.generic import TemplateView

class CreateTeam(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "team_leader","members","date_created","description")
    model = Team


class SingleTeam(generic.DetailView):
    model = Team


class ListTeams(generic.ListView):
    model = Team

class JoinTeam(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("teams:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        team = get_object_or_404(Team, slug=self.kwargs.get("slug"))

        try:
            TeamMember.objects.create(user=self.request.user, team=team)

        except IntegrityError:
            messages.warning(
                self.request, ("Warning, already a member of {}".format(team.name)))

        else:
            messages.success(
                self.request, "You are now a member of the {} team.".format(team.name))

        return super().get(request, *args, **kwargs)


class LeaveTeam(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("teams:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.TeamMember.objects.filter(
                user=self.request.user,
                team__slug=self.kwargs.get("slug")
            ).get()

        except models.TeamMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this team because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this team."
            )
        return super().get(request, *args, **kwargs)

teams/templates/teams/team_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% block preteam %}{% endblock %} 
    {% block team_content %}{% endblock %}
    {% block postteam %}{% endblock %}
  </div>
</div>
{% endblock %}

teams/templates/teams/team_detail.html
{% extends "teams/team_base.html" %}

{% block preteam %}
<table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Team Name</th>
          <th>Team Leader</th>
          <th>Total Member</th>
          <th>Team Members</th>
        </tr>
      </thead>
      <tbody>
        
        <tr>
          <td>
              {{team.name}}
          </td>
          <td>{{team.team_leader}}</td>
          <td>{{team.members.count}}</td>
          <td>
          {% for member in team.members.all %}
          <li>{{ member }}</li>
           {% endfor %}
          </td>
        </tr>
     
      </tbody>
    </table>

{% endblock %}


{% block team_content %}

<div class="col-md-8">
	{% if team.trips.count == 0 %}
	<h2>No trip activity created in this team yet!</h2>

	{% else %}

		{% for trip in team.trips.all %}
      <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Team Name</th>
          <th>Location</th>
          <th>Category</th>
          <th>Number</th>
          <th>Cost</th>
          <th>Reason</th>
          <th>initiator</th>
          <th>created_at</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        <td><a href="{% url 'teams:single' slug=trip.team.slug %}">{{ trip.team.name }}</a></td>
          <td>
            {{trip.location}}
          </td>
          <td>{{trip.category}}</td>
          <td>{{trip.number}}</td>
          <td>{{trip.cost}}</td>
          <td>{{trip.reason_html|safe }}</td>
          <td><span class="username"
        ><a href="{% url 'trips:for_user' username=trip.user.username %}"
          >@{{ trip.user.username }}</a
        ></span
      ></td>
          <td>{{ trip.created_at }}</td>
        </tr>
    
      </tbody>
    </table>
			
		{% endfor %}

	{% endif %}
</div>
 <div class="content">
				{% if user in team.members.all %}
					<a href="{% url 'teams:leave' slug=team.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'teams:join' slug=team.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}
</div>
{% endblock %}

teams/templates/teams/team_form.html
{% extends "teams/team_base.html" %} 
{% load bootstrap3 %}
{% block team_content %}
<h2>Create A New Team :</h2>

<form method="POST" action="{% url 'teams:create' %}" id="teamForm">
  {% csrf_token %} {% bootstrap_form form %}
  <input type="submit" value="Create" class="btn btn-primary btn-large" />
</form>
{% endblock %}

teams/templates/teams/team_list.html
{% extends "teams/team_base.html" %} {% block preteam %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h2>
      Welcome <a href="{% url 'trips:for_user' username=user.username %}"
        >@{{user.username }}</a>: All the Travel Teams >>>
      
    </h2>

    {% endif %}
    <h2>Teams</h2>

    <p>Teams Page: Select a Travel Team ^ ^</p>
  </div>
  {% if user.is_authenticated %}
  <a href="{% url 'teams:create' %}" class="btn btn-md btn-fill btn-warning"
    ><span class="glyphicon glyphicon-plus-sign"></span> Create New Team!</a
  >
  {% endif %}
</div>
{% endblock %} {% block team_content %}
<div class="col-md-8">
  <div class="list-team">
    {% for team in object_list %}
    <a class="list-team-item" href="{% url 'teams:single' slug=team.slug %}">
      <h3 class="title list-team-item-heading">{{ team.name }}</h3> </a>
      <h6 class="title list-team-item-heading">{{ team.team_leader }}</h6>
      <div class="list-team-item-text container-fluid">
        
        <div class="row">
          <div class="col-md-4">
            <span class="badge">
              {% for member in team.members.all %}
              <li>{{ member }}</li>
              {% endfor %}
            </span> 
          </div>
          <div class="col-md-4">
            <ol><span class="badge">Activities: {% for trip in team.trips.all %}
              <li>{{ trip }}</li>
              {% endfor %}</span> </ol>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}