accounts/urls.py
#from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

django_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^trips/", include("trips.urls", namespace="trips")),
    url(r"^teams/", include("teams.urls", namespace="teams")),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'

urlpatterns = [
    url(r"^$", views.ListTeams.as_view(), name="all"),
    url(r"^new/$", views.CreateTeam.as_view(), name="create"),
    url(r"^trips/in/(?P<slug>[-\w]+)/$",
        views.SingleTeam.as_view(), name="single"),
    url(r"join/(?P<slug>[-\w]+)/$", views.JoinTeam.as_view(), name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$", views.LeaveTeam.as_view(), name="leave"),
]

trips/urls.py
from django.conf.urls import url

from . import views

app_name = 'trips'

urlpatterns = [
    url(r"^$", views.TripList.as_view(), name="all"),
    url(r"new/$", views.CreateTrip.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",
        views.UserTrips.as_view(), name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",
        views.TripDetail.as_view(), name="single"),
    url(r"delete/(?P<pk>\d+)/$", views.DeleteTrip.as_view(), name="delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{% static 'django_project/static/css/master.css' %}"
    />
    <title>Trips planning</title>
  </head>
  <body>
    <nav class="navbar mynav" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Trip Planning</a>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'trips:create' %}" class="btn btn-simple"
              >Create Trip</a
            >
          </li>

          <li>
            <a href="{% url 'teams:all' %}" class="btn btn-simple">Teams</a>
          </li>
          <li>
            <a href="{% url 'teams:create' %}" class="btn btn-simple"
              >Create Team</a
            >
          </li>
          <li>
            <a href="{% url 'trips:for_user' user.username %}" class="btn btn-simple"
              >My Trips</a
            >
          </li>
          <li>
            <a href="{% url 'accounts:logout' %}" class="btn btn-simple"
              >Log out</a
            >
          </li>
          {% else %}
          <li>
            <a href="{% url 'teams:all' %}" class="btn btn-simple">Teams</a>
          </li>
          <li>
            <a href="{% url 'accounts:login' %}" class="btn btn-simple"
              >Log in</a
            >
          </li>
          <li>
            <a href="{% url 'accounts:signup' %}" class="btn btn-simple"
              >Sign up</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mycontent">{% block content %} {% endblock %}</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<div class='container'>
    <div class="jumbotron">
        <h5 class="display-4">Welcome to our corporate travel management platform!</h5>
        <p class="lead">Get to know amazing features to reduce your travel cost, manage risk ,track location and many more.</p>
        <hr class="my-4">
        <p> Fast, Efficient, Secure! </p>
        <a class="btn btn-primary btn-sm" id='One' href="#" role="button">Learn more about Trip Approve</a>
        <div class="box fourteen-nine">
    </div>
</div>


    <div class='container'>
        <video src="{% static 'Trip.mp4' %}" autoPlay="true" muted></video>
    </div>


	<h4>follow us
    <h4>on Youtube*</h4>
    <h4>id: Trip Approve</h4>
  <p> </p>
  <a href="https://youtube.com"><button id='Linkedin' type="button" class="btn btn-info" >Youtube</button></a>
  </div>
  

{% endblock %}

templates/test.html
{% extends "teams/team_base.html" %} 
{% block preteam %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h2>
      Welcome <a href="{% url 'trips:for_user' username=user.username %}"
        >{{user.username }} </a> 
    </h2>
    <h2>  >>> </h2>

    {% endif %}
    

</div>
  {% if user.is_authenticated %}
  <a href="{% url 'teams:create' %}" class="btn btn-md btn-fill btn-warning"
    ><span class="glyphicon glyphicon-plus-sign"></span> Create New Travel Team!</a
  >
  <a href="{% url 'trips:for_user' user.username %}" class="btn btn-md btn-fill btn-warning">My Trips</a>
  
  {% endif %}
</div>
{% endblock %} 

{% block team_content %}
<div class="col-md-8">
  <div class="list-team">
  
    {% for team in object_list %}
    <a class="list-team-item" href="{% url 'teams:single' slug=team.slug %}">
      <h3 class="title list-team-item-heading">{{ team.name }}</h3>
      <h4 class="title list-team-item-heading">{{ team.team_leader }}</h4>
      <div class="list-team-item-text container-fluid">
        
        <div class="row">
          <div class="col-md-4">
            <span class="badge">
              {% for member in team.members.all %}
              <li>{{ member }}</li>
              {% endfor %}
            </span> 
          </div>
          <div class="col-md-4">
            <span class="badge">Activities: {% for trip in team.trips.all %}
              <li>{{ trip }}</li>
              {% endfor %}</span> 
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %} {% block content %}
<h1>Thanks for visiting Trip Approve, please come back soon ^ * ^</h1>
{% endblock %}